version: 0.2

env:
  variables:
    DATA_BUCKET: dog-shelter-tamagochi-ai-data
    FRONTEND_BUCKET: dog-shelter-tamagochi-ai-frontend
    ECR_REPO: dog-shelter-tamagochi-ai-api
  # set GROQ_API_KEY as environment variable in the CodeBuild project

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo Installing frontend dependencies...
      - cd frontend && npm install && cd ..

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO ./api
      - docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:latest
      - echo Building React frontend...
      - export VITE_API_URL=$(aws cloudformation describe-stacks --stack-name dog-shelter-tamagochi-ai --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text | sed 's:/*$::')
      - cd frontend && npm run build && cd ..

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPO:latest
      - echo Writing image URI for CloudFormation Deploy stage...
      - IMAGE_DIGEST=$(aws ecr describe-images --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageDigest' --output text)
      - printf '{"ImageUri":"%s"}' "$ECR_REGISTRY/$ECR_REPO@$IMAGE_DIGEST" > imageUri.json
      - echo Syncing frontend to S3...
      - aws s3 sync frontend/dist/ s3://$FRONTEND_BUCKET --delete
      - echo Invalidating CloudFront cache...
      - CLOUDFRONT_ID=$(aws cloudformation describe-stacks --stack-name dog-shelter-tamagochi-ai --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo Build complete, handing off to Deploy stage...

# imageUri.json is passed to the CodePipeline Deploy stage so CloudFormation can update
# the Lambda image URI without needing a placeholder or manual input
artifacts:
  files:
    - imageUri.json

# NOTE: I'm not uploading the .parquet or chroma_db/ files in buildspec.yml bc theyre static and dont change much and are TOO BIG
# if i update the .parquet or chroma_db/ files, I can reupload them with these commands (which i have to do before first github push anyways)
  # aws s3 cp pipeline/data/processed/breed_profiles.parquet s3://dog-shelter-tamagochi-ai-data/
  # aws s3 sync ragpipeline/data/chroma_db/ s3://dog-shelter-tamagochi-ai-data/chroma_db/
  